### ISSUE TITLE
Add assertions for checking dom node classes

### ISSUE THREAD

**Issue by iamrandys** [percyhanna/chai-react#1]
Nice react assertion package! Are you interested in adding assertions to check DOM node classes.  I've search around and haven't found anything to solve this need.  I've created three assertions to check DOM node classes.  It would be great to add them to what you have and move them out of my code.

I could also add more documentation to your readme.md, if you'd like.

**For a given DOM node:**

    <div class="class-a class-b class-c"></div>

to.have.classes
----

The classes in the DOM node must exactly match the expected class names.

    expect(domComponent.getDOMNode()).to.have.classes(['class-b', 'class-a', 'class-c']);  // SUCCESS
    expect(domComponent.getDOMNode()).to.have.classes(['class-b', 'class-a']);             // FAIL

to.containClasses
----

The classes in the DOM node just need contain the expected classes.

    expect(domComponent.getDOMNode()).to.containClasses(['class-b', 'class-c']);  // SUCCESS
    expect(domComponent.getDOMNode()).to.containClasses(['class-b', 'class-d']);  // FAIL

to.containClass
----

The classes in the DOM node just needs to contain the expected class.

    expect(domComponent.getDOMNode()).to.containClass('class-c');  // SUCCESS
    expect(domComponent.getDOMNode()).to.containClass('class-d');  // FAIL

**Comment by percyhanna** [comment]
@iamrandys I think [`rquery`](https://github.com/percyhanna/rquery) will do exactly what you want, and even do it better. You can write CSS/jQuery-like selectors to find components:

```javascript
expect($R(myComponent, '.class-b')).to.have.length(2);
```

**Comment by iamrandys** [comment]
Oh this is nice!  We actually started developing something that is similar but not nearly as feature rich just last week.  You developed this just in time :) I'll have to take it for a spin.

Thanks!!

**Comment by percyhanna** [comment]
Awesome! Let me know how it goes! I want to keep adding to `rquery` as well as adding to `chai-react` to help them complement each other.
