### ISSUE TITLE
Warnings with React 0.14

### ISSUE THREAD

**Issue by yannickcr** [percyhanna/chai-react#11]
We had a few issue when using `chai-react` with React 0.14:

* The deprecated `React.addons.TestUtils` is used in `chai-react.js`

 > Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.
* Warning when using `componentsWithProp`

 > Warning: ReactDOMComponent: Do not access .props of a DOM node; instead, recreate the props as `render` did originally or read the DOM properties/attributes directly from this node (e.g., this.refs.box.className).

**Comment by percyhanna** [comment]
Hi Yannick, thanks for bringing this to my attention. I had been following the v0.14 release and hadn't gotten around to checking/updating `chai-react` to make sure it works accordingly.

I've put together a PR (#12) to attempt to fix the warnings and update to v0.14. Are you able to test this out locally to see if it addresses your issues?

Thanks.

**Comment by yannickcr** [comment]
Thanks, PR #12 seems to fixes the warnings.

I added a single note to the commit, there is an error in the AMD parameters (I did not test since we do not use AMD).

**Comment by percyhanna** [comment]
Closed by #12, released as v3.0.0. Thanks @yannickcr!
