### ISSUE TITLE
Add assertions for checking component types

### ISSUE THREAD

**Issue by valscion** [percyhanna/chai-react#3]
First of all: Wow, these matchers look very promising! I intend to use them to the greatest extent as possible.

However, I find that some basic assertions are missing and was wondering whether it would be possible to add assertions for checking a type of a component, mainly `TestUtils.isComponentOfType()`.

As many of the test utility methods mentioned in [Reacts Test Utilities page](http://facebook.github.io/react/docs/test-utils.html) seem to be missing, I was wondering whether you have an intention to implement them at some point in the future?

I'm also open for creating PRs for missing functionality as I go along and need them in our project, if that is OK for you. You could also benefit from an improved readme, like the one in [`chai-jquery`](https://github.com/chaijs/chai-jquery/), perhaps?

**Comment by percyhanna** [comment]
Hi @valscion, you may be interested in checking out another testing library I wrote called [`rquery`](https://github.com/percyhanna/rquery). I find it even easier to write tests now by combining `rquery` and `chai-react` together. `rquery` is used to traverse the React tree, and `chai-react` is used to make assertions.

**Comment by valscion** [comment]
Wow, seems very promising! I'll keep an eye on `rquery` and probably start using it in future tests to see how it holds up. Thanks for the tip!
