### ISSUE TITLE
Last version supporting React 0.12 is not published to npm

### ISSUE THREAD

**Issue by valscion** [percyhanna/chai-react#7]
I was trying to install version 1.0.5 as it is the latest to support React 0.12, but that doesn't seem to be published to npm. Could you publish that so we could still use the version which supports 0.12 with npm installation?

Thanks.

**Comment by percyhanna** [comment]
My apologies. Should be published now.

**Comment by valscion** [comment]
Thanks! And thanks for this matcher, it really helps us write cleaner tests.
