### ISSUE TITLE
Karma integration

### ISSUE THREAD

**Issue by kristian-puccio** [percyhanna/chai-react#8]
I'm trying to use chai-react inside karma without much luck.

I spotted this https://github.com/princed/karma-chai-plugins and tried extending it to load chai-react but I get a ` ReferenceError: Can't find variable: React`.

Any ideas?

**Comment by percyhanna** [comment]
`chai-react` should support [CommonJS/Node](https://github.com/percyhanna/chai-react/blob/master/chai-react.js#L5), [RequireJS/AMD](https://github.com/percyhanna/chai-react/blob/master/chai-react.js#L8-12), and standard [global/module](https://github.com/percyhanna/chai-react/blob/master/chai-react.js#L15-17) formats.

Given the error message, it is likely falling back to the default global/module implementation, meaning that you don't have the [`React` module defined globally](https://github.com/percyhanna/chai-react/blob/master/chai-react.js#L16).

I recently dealt with a support issue for someone trying to use `rquery` with Karma. They [defined React globally](https://github.com/steffenmllr/rquery-issue/blob/master/tests/globals.js#L4) and then load that as part of their [Karma config](https://github.com/steffenmllr/rquery-issue/blob/master/tests/karma.config.js). Hopefully that helps out?

**Comment by kristian-puccio** [comment]
Works perfectly, thanks!

**Comment by kristian-puccio** [comment]
Awesome thanks for that worked perfectly.
